apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-serv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: tickets.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-serv
              servicePort: 3000
          - path: /api/tickets/?(.*)
            backend:
              serviceName: tickets-serv
              servicePort: 3000
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-serv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-serv
              servicePort: 3000
