apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: jason1196/tickets
          env:
            - name: NATS_URL
              value: "http://nats-serv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AWS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-akey
                  key: AWS_KEY
            - name: AWS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-akeyid
                  key: AWS_KEY_ID
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-serv:27017/tickets"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-serv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
