name: deploy-auth
on: 
  push:
    branches: 
      - master
    paths: 
      - 'auth/**'
jobs: 
  build:
    
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd auth &&  docker build -t jason1196/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}    
      - run: docker push jason1196/auth 
      - uses: actions/checkout@master
      - name: Setup Linode cli
        uses: brendon1555/setup-linode-cli@master
        with:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      - run: linode-cli --help
        
